insert into Lecturer(id, name, shortcut) values(1, 'Jerzy Raszka', 'JR');
insert into Lecturer(id, name, shortcut, title) values(2, 'S Fialko', 'SF', "Dr hab. inż.");
insert into Lecture_type(id, name, shortcut) values(1, 'Wykład', 'Wyk');
insert into Lecture_type(id, name, shortcut) values(2, 'Ćwiczenia', 'Ćw');
insert into Lecture_type(id, name, shortcut) values(3, 'Laboratorium', 'L');
insert into Lecture_type(id, name, shortcut) values(4, 'Projekt', 'Proj');
insert into Lecture_name(id, name, shortcut) values(1, 'Podstawy Baz Danych', 'PBD');
insert into Lecture_name(id, name, shortcut) values(2, 'Języki i Paradygmaty Progamowania', 'JiPP');
insert into Lecture_name(id, name, shortcut) values(3, 'Pracownia Problemowa', 'PP');
insert into Lecture_name(id, name, shortcut) values(4, 'Inteligentne Narzędzia Informatyczne', 'INI');